const wordlist = ["naar","media","meest","oorlog","formule","films","boek","kind","eten",
"alphen","over","laatste","nieuws","eerst","live","boeken","meer","vliegtickets","andere",
"luchthavens","whatsapp","delen","facebook","twitter","linkedin","vakantiegangers","hebben",
"afgelopen","tijd","vluchten","geboekt","vertrekken","vanaf","schrijft","donderdag","basis",
"cijfers","onder","eigenaar","boekingssites","cheaptickets","airport","aantal","boekingen",
"sites","travix","eerste","dagen","procent","stijgen","opzichte","rotterdam","hague","steeg",
"dezelfde","periode","veruit","grootste","luchthaven","zoekopdrachten","waarbij","mensen",
"niet","direct","vlucht","kwam","schiphol","slechter","voren","vliegreizen","ondanks","naderende",
"veel","gezocht","eindhoven","noteerden","stijging","respectievelijk","tickets","voor","duitsland",
"werd","kampt","grote","weken","meermaals","negatief","gekomen","door","chaos","groot","daardoor",
"ontstonden","combinatie","wilde","staking","bagagepersoneel","problemen","reizigers","moesten",
"uren","staan","tientallen","werden","woensdag","tegen","drukte","waarschijnlijk","aanhoudt",
"kunnen","gedurende","maken","krijgen","langere","rijen","wachten","langer","uitgelichte",
"gisteren","trend","liever","vliegen","even","mijden","jaren","wordt","absurde","wachtrijen",
"extra","comfort","reizen","kleinere","zoveel","heerst","geen","chaotische","dicht","hebt",
"minder","last","overvol","uitvallend","openbaar","peperdure","onbetrouwbare","drukke","parkeerkrapte",
"torenhoge","loopafstanden","pieren","zijn","wachttijden","bagage","beveiliging","comfortabel",
"lang","verleden","moet","regelmatig","steden","europa","vooruit","behoorlijk","goedkope","weinig",
"betalen","maar","nogal","vloog","eens","vroege","avond","koopt","ticket","vliegtuig","vertrekt","soms",
"gelijk","saga","schiphel","schande","vanuit","schagen","rijd","effe","goedkoper","verliep","vrijdag","bull",
"ferrari","bouwman","beleeft","droomdag","woorden","achter","duidelijk","iets","graaf","teleurstellend","drie",
"gewonden","sprookjesbos","valkenburg","vallend","neemt","uitdrukkelijke","instemming","seks","verplicht",
"sekteleider","charles","manson","mogelijk","ruim","halve","eeuw","hypotheekrente","lijkt","voorbij","stuurt",
"toch","geavanceerde","raketsystemen","werkt","zware","raketlanceersysteem","ongeluk","attractie","kapseist",
"tijdens","zeilwedstrijd","vliegt","aanrijding","lucht","raakt","motor","contact",

]

export default wordlist;